tasks:
  - command: |
      while [ -z "$ASTRA_REGION" ] ; do
        printf "\n❗ The ASTRA_REGION environment variable is required. Please enter its value.\n" &&
        read -s -p "ASTRA_REGION: " ASTRA_REGION ;
      done ; gp env ASTRA_REGION=$ASTRA_REGION && printf "\nThanks\n"

      while [ -z "$ASTRA_DATABASE_ID" ] ; do
        printf "\n❗ The ASTRA_DATABASE_ID environment variable is required. Please enter its value.\n" &&
        read -s -p "ASTRA_DATABASE_ID: " ASTRA_DATABASE_ID ;
      done ; gp env ASTRA_DATABASE_ID=$ASTRA_DATABASE_ID && printf "\nThanks\n"

      while [ -z "$ASTRA_DATABASE_USERNAME" ] ; do
        printf "\n❗ The ASTRA_DATABASE_USERNAME environment variable is required. Please enter its value.\n" &&
        read -s -p "ASTRA_DATABASE_USERNAME: " ASTRA_DATABASE_USERNAME ;
      done ; gp env ASTRA_DATABASE_USERNAME=$ASTRA_DATABASE_USERNAME && printf "\nThanks\n"

      while [ -z "$ASTRA_DATABASE_PASSWORD" ] ; do
        printf "\n❗ The ASTRA_DATABASE_PASSWORD environment variable is required. Please enter its value.\n" &&
        read -s -p "ASTRA_DATABASE_PASSWORD: " ASTRA_DATABASE_PASSWORD ;
      done ; gp env ASTRA_DATABASE_PASSWORD=$ASTRA_DATABASE_PASSWORD && printf "\nThanks\n"

  - init: pip3 install -r backend/requirements.txt
    command: cd backend && python3 main.py
    
ports:
  - port: 5000
    onOpen: ignore

vscode:
  extensions:
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==
